# Generated by Django 3.0.6 on 2020-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0004_auto_20200510_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/Users/roberthemming/SourceCode/Python/WebServers/BobbyWebServer/static/images/user-xxl.jpg', null=True, upload_to=''),
        ),
    ]
