# Generated by Django 3.0.6 on 2020-05-11 15:19

import Blogging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0005_auto_20200510_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/user-xxl.jpg', upload_to=Blogging.models.upload_location),
        ),
    ]
