# Generated by Django 3.0.6 on 2020-05-11 17:29

import Blogging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0007_auto_20200511_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/Users/roberthemming/SourceCode/Python/WebServers/BobbyWebServer/static/images/user-xxl.jpg', upload_to=Blogging.models.upload_location),
        ),
    ]
