# Generated by Django 3.0.6 on 2020-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0008_auto_20200511_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-xxl.jpg', upload_to='static/images/'),
        ),
    ]
