# Generated by Django 3.0.6 on 2020-05-22 12:28

import Blogging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0009_auto_20200521_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-xxl.jpg', null=True, upload_to=Blogging.models.upload_location),
        ),
    ]
