# Generated by Django 3.0.6 on 2020-05-22 13:19

import Blogging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0011_auto_20200522_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to=Blogging.models.upload_location),
        ),
    ]
